### PR TITLE
fix: fix error when replacing txt file with lrc file

### LINKED ISSUE #25: [BUG] Saving txt lyrics multiple times can cause OS error: no such file or directory
**Describe the bug**
When lrxed overwrites a txt file, upon leaving to file browser and returning to edit those same lyrics, you will not be able to save because the .txt file is now missing. It should indeed be missing but lrxed assumes it shouldn't be.

**To Reproduce**
1. Set settings.replace-txt-file-on-save to true
2. Open lrxed in file browser mode
3. Browse to and open lyrics that are saved in a .txt file
4. Save the file, it will now be deleted and replaced with a .lrc file
5. Return to the file browser
6. Once again open the same lyrics
7. Try to save, see error

**Expected behavior**
The .lrc file gets saved and overwritten like usual.

### PR DESCRIPTION
**Pull request by toodeluna**
This PR does the following things:
- Replaces the `lyrics_state` with a `song_state` that stores the current song instead of just the lyrics.
- Get rid of the `RefCell` stuff in the `file_browser_state` and use a getter function instead.
- Fixes the issue that occurs when a txt file is replaced with an lrc file and then saved again from the editor.

Closes #25

### CODE REVIEW

File: src/state/file_browser_state.rs [hunk 1]
```diff
@@ -92,35 +104,33 @@ impl FileBrowserState {
...
-	pub fn update_selected_lyrics(&mut self, lyrics: &Lyrics) {
-		if let Some(FileBrowserItem::Song(song)) = self
-			.items
-			.borrow_mut()
-			.get_mut(self.cursor.pos().y as usize)
-		{
-			song.lyrics = Some(lyrics.clone());
-		}
-	}
+	pub fn update_selected_lyrics(&mut self, new_song: Song) {
```
Comment (LunaPresent) [inline src/state/file_browser_state.rs:129]: rename to update_selected_song

**Review by LunaPresent — APPROVED** [review]
this is good news
